/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tema17_2;

import java.awt.Component;
import java.awt.Point;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

public class JFrameMain extends javax.swing.JFrame {

    public TableModelPeliculas tableModel;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {

        /**
         *  COMENTAR 
         */
        try {
            ConexionMySQL.crearConexion("localhost", "3308", "root", "", "catalago");
            ConexionMySQL.getInstance().conectar();
            tableModel = new TableModelPeliculas();
            
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }

         /**
         *  COMENTAR 
         */
        initComponents();

         /**
         *  COMENTAR 
         */
        ImageIcon icon = new ImageIcon("src/images/icons/film.png");
        setIconImage(icon.getImage());

        /**
         *  COMENTAR 
         */
        jpumOperacionesTabla.addPopupMenuListener(new PopupMenuListener() {

            // Función anónima
            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
                // Hace que el método de run se ejecute en el hilo de swing
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        int rowAtPoint = jtPeliculas.rowAtPoint(SwingUtilities.convertPoint(jpumOperacionesTabla, new Point(0, 0), jtPeliculas));
                        if (rowAtPoint > -1) {
                            // Seleccionamos la fila en la cual se ha clicado
                            jtPeliculas.setRowSelectionInterval(rowAtPoint, rowAtPoint);
                        }
                    }
                });
            }

            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                // TODO Auto-generated method stub
            }

            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {
                // TODO Auto-generated method stub
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpumOperacionesTabla = new javax.swing.JPopupMenu();
        jmiBorrar = new javax.swing.JMenuItem();
        jmiEditar = new javax.swing.JMenuItem();
        jpNorth = new javax.swing.JPanel();
        jpFields = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jpAño = new javax.swing.JPanel();
        jlAño = new javax.swing.JLabel();
        jtfAño = new javax.swing.JTextField();
        jlPuntuacion = new javax.swing.JLabel();
        jcbPuntuacion = new javax.swing.JComboBox<>();
        jpSinopsis = new javax.swing.JPanel();
        jlSinopsis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaSinopsis = new javax.swing.JTextArea();
        jpBotones = new javax.swing.JPanel();
        jbAdd = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPeliculas = new javax.swing.JTable();

        jmiBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/remove.png"))); // NOI18N
        jmiBorrar.setText("Borrar");
        jpumOperacionesTabla.add(jmiBorrar);

        jmiEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/edit.png"))); // NOI18N
        jmiEditar.setText("Editar");
        jpumOperacionesTabla.add(jmiEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catálogo de Cine");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpNorth.setLayout(new java.awt.BorderLayout());

        jpTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTitulo.setText("Título:");
        jlTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        jlTitulo.setMaximumSize(new java.awt.Dimension(20, 14));
        jlTitulo.setMinimumSize(new java.awt.Dimension(20, 14));
        jlTitulo.setPreferredSize(new java.awt.Dimension(60, 25));
        jpTitulo.add(jlTitulo);

        jtfTitulo.setColumns(20);
        jtfTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        jpTitulo.add(jtfTitulo);

        jpAño.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlAño.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlAño.setText("Año:");
        jlAño.setMaximumSize(new java.awt.Dimension(20, 14));
        jlAño.setMinimumSize(new java.awt.Dimension(20, 14));
        jlAño.setPreferredSize(new java.awt.Dimension(60, 25));
        jpAño.add(jlAño);

        jtfAño.setColumns(5);
        jpAño.add(jtfAño);

        jlPuntuacion.setText("Puntuación:");
        jpAño.add(jlPuntuacion);

        jcbPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jpAño.add(jcbPuntuacion);

        jpSinopsis.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jlSinopsis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlSinopsis.setText("Sinopsis:");
        jlSinopsis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlSinopsis.setMaximumSize(new java.awt.Dimension(20, 14));
        jlSinopsis.setMinimumSize(new java.awt.Dimension(20, 14));
        jlSinopsis.setPreferredSize(new java.awt.Dimension(60, 25));
        jpSinopsis.add(jlSinopsis);

        jtaSinopsis.setColumns(20);
        jtaSinopsis.setRows(5);
        jScrollPane2.setViewportView(jtaSinopsis);

        jpSinopsis.add(jScrollPane2);

        javax.swing.GroupLayout jpFieldsLayout = new javax.swing.GroupLayout(jpFields);
        jpFields.setLayout(jpFieldsLayout);
        jpFieldsLayout.setHorizontalGroup(
            jpFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpAño, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpFieldsLayout.setVerticalGroup(
            jpFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFieldsLayout.createSequentialGroup()
                .addComponent(jpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpNorth.add(jpFields, java.awt.BorderLayout.WEST);

        jbAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/add.png"))); // NOI18N
        jbAdd.setText("Añadir");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });
        jpBotones.add(jbAdd);

        jbClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/clear.png"))); // NOI18N
        jbClear.setText("Limpiar");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });
        jpBotones.add(jbClear);

        jpNorth.add(jpBotones, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpNorth, java.awt.BorderLayout.NORTH);

        jtPeliculas.setModel(tableModel);
        jtPeliculas.setComponentPopupMenu(jpumOperacionesTabla);
        jtPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jtPeliculas);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        if (jtfTitulo.getText().trim().isEmpty() || jtfAño.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rellene los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String titulo = jtfTitulo.getText();
            int año = Integer.parseInt(jtfAño.getText());
            int puntuacion = jcbPuntuacion.getSelectedIndex() + 1;
            String sinopsis = jtaSinopsis.getText();
            try {
                tableModel.insertar(titulo, año, puntuacion, sinopsis);
            } catch (SQLException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        jtfTitulo.setText("");
        jtfAño.setText("");
        jcbPuntuacion.setSelectedIndex(0);
        jtaSinopsis.setText("");
    }//GEN-LAST:event_jbClearActionPerformed

    /**
     * COMENTAR 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ConexionMySQL.getInstance().conectar();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameMain mainFrame = new JFrameMain();
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbClear;
    private javax.swing.JComboBox<String> jcbPuntuacion;
    private javax.swing.JLabel jlAño;
    private javax.swing.JLabel jlPuntuacion;
    private javax.swing.JLabel jlSinopsis;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JMenuItem jmiBorrar;
    private javax.swing.JMenuItem jmiEditar;
    private javax.swing.JPanel jpAño;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpFields;
    private javax.swing.JPanel jpNorth;
    private javax.swing.JPanel jpSinopsis;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPopupMenu jpumOperacionesTabla;
    private javax.swing.JTable jtPeliculas;
    private javax.swing.JTextArea jtaSinopsis;
    private javax.swing.JTextField jtfAño;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
